Hrnet debug
opencap-org/opencap-core pull request #111
Opened 2023-09-19 05:58 UTC by suhlrich

1) use box-based keypoint tracker with hrnet, (after both box and pose are run)
2) nan low-confidence markers in largest bbox identifier algo (otherwise, spurious keypoints -> large bbox). Seems like openpose may be using .5 confidence threshold for 0s/nans. 
3) solve glob.glob problem with visualizer videos if multiple pose models run locally

2023-09-20 14:13 UTC, antoinefalisse requested changes
Great, just added one comment.

2023-09-22 20:18 UTC, suhlrich commented on Examples/print_log.txt
will delete b4 merge

2023-09-22 20:18 UTC, suhlrich commented on Examples/reprocessSessions.py
will revert this before merge

2023-09-22 23:40 UTC, antoinefalisse requested changes
Great, two comments.

2023-09-22 23:40 UTC, antoinefalisse commented on main.py
> +            vertical_offset_settings = float(np.copy(vertical_offset))
[For consistency](https://github.com/stanfordnmbl/opencap-core/blob/main/utilsAugmenter.py#L160), I think this should be `vertical_offset_settings = float(np.copy(vertical_offset)) - 0.01`.

2023-09-22 23:40 UTC, antoinefalisse commented on main.py
> +        settings['verticalOffset'] = vertical_offset_settings
This will crash if `vertical_offset_settings ` does not exist, which will be the case if `offset == False`. Could do 

```
if not extrinsicsTrial and offset:
  settings['verticalOffset'] = vertical_offset_settings 
  with open(pathSettings, 'w') as file:
      yaml.dump(settings, file)

2023-09-23 06:56 UTC, suhlrich commented
@antoinefalisse Thanks. Changes made. We can merge and test monday.

2023-09-25 18:46 UTC, antoinefalisse approved these changes

2023-09-25 18:47 UTC, merged